# Generated by Django 3.2.7 on 2021-09-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_new_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
